# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  golang-ci: circleci/go@1.5.0

jobs:
  test:
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/justinw33/testing
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
            # - echo-output
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build:
    docker: 
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/justinw33/testing
    steps:
      - attach_workspace:
          at: /go/src/github.com/justinw33/testing
      # - checkout
      - run: go build .
  deploy:
    working_directory: /go/src/github.com/justinw33/testing
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: 
          name: Set up gcloud config
          command: |
            echo ${GCLOUD_KEY} | base64 --decode | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT}
            gcloud --quiet config set compute/region ${GCLOUD_ZONE}
      - deploy:
          name: deploying app engine
          command: gcloud app deploy app.yaml

workflows:
  main:
    jobs:
      - test
      - build:
          requires:
            - test 
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
